name: Build

on:
  workflow_dispatch:

jobs:
  #build:
  #  name: Build
  #  runs-on: ubuntu-latest
  #
  #  steps:
  #    - name: Checkout repository code
  #      uses: actions/checkout@v4
  #
  #    - name: Setup Node.js
  #      uses: actions/setup-node@v4
  #      with:
  #        node-version: '20.x'
  #
  #    - name: Build
  #      run: npm ci && npm run build

  unit-test:
    name: Sonar Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true
