#
# Contains jobs that execute a release.
#

name: Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: The sem-ver of this release
        required: true
        type: string

jobs:

  #
  # Job to create the GitHub release package for this specific release.
  # Will create a GitHub release tagged with the release name and include the following assets:
  #
  # - Source code archives (.zip and .tar.gz)
  # - Fat Jar
  #
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build npm project
        run: npm run build

      - name: Zip dist folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ./dist dist.zip

      - name: Create Tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.releaseVersion }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          repository: my-own-lawbook/web-client
          files: ./dist.zip
          body: <Create changelog>
          body_path: ./changelogs/${{ inputs.releaseVersion }}.md
          name: ${{ inputs.releaseVersion }}
          tag_name: ${{ inputs.releaseVersion }}

  #
  # Job to publish an image to the GitHub container registry (ghcr.io).
  #
  publish-image:
    name: Publish Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        shell: bash
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Image
        shell: bash
        run: docker build -t ghcr.io/${{ github.repository }}:${{ inputs.releaseVersion }} .

      - name: Push to Registry
        shell: bash
        run: docker push ghcr.io/${{ github.repository }}:${{ inputs.releaseVersion }}